stages:
- "test"

before_script:
- apt-get update
- apt-get install redis-server -y
- redis-server --daemonize yes
- python -V
- pip install tox

test-3.6:
  image: python:3.6-buster
  script:  
  - tox -e py36

test-3.7:
  image: python:3.7-buster
  script:  
  - tox -e py37

test-3.8:
  image: python:3.8-buster
  script:  
  - tox -e py38

test-flake8:
  image: python:3.8-buster
  script:  
  - tox -e flake8

